// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.27.2
// source: stats.proto

package statspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests  int32                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`   // total number of requests received
	FibonacciStats []*FibonacciStat       `protobuf:"bytes,2,rep,name=fibonacci_stats,json=fibonacciStats,proto3" json:"fibonacci_stats,omitempty"` // per-number stats
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *StatsResponse) GetTotalRequests() int32 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *StatsResponse) GetFibonacciStats() []*FibonacciStat {
	if x != nil {
		return x.FibonacciStats
	}
	return nil
}

// Nested message for per-number stats
type FibonacciStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`                                                 // Fibonacci number requested
	RequestCount  int32                  `protobuf:"varint,2,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`       // How many times it was requested
	AverageTimeMs float64                `protobuf:"fixed64,3,opt,name=average_time_ms,json=averageTimeMs,proto3" json:"average_time_ms,omitempty"` // Average computation time in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FibonacciStat) Reset() {
	*x = FibonacciStat{}
	mi := &file_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FibonacciStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FibonacciStat) ProtoMessage() {}

func (x *FibonacciStat) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FibonacciStat.ProtoReflect.Descriptor instead.
func (*FibonacciStat) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{1}
}

func (x *FibonacciStat) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *FibonacciStat) GetRequestCount() int32 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *FibonacciStat) GetAverageTimeMs() float64 {
	if x != nil {
		return x.AverageTimeMs
	}
	return 0
}

type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"` // input number
	Duration      int64                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{2}
}

func (x *RecordRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *RecordRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type RecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // record result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{3}
}

func (x *RecordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_stats_proto protoreflect.FileDescriptor

const file_stats_proto_rawDesc = "" +
	"\n" +
	"\vstats.proto\x12\x05stats\x1a\x1bgoogle/protobuf/empty.proto\"u\n" +
	"\rStatsResponse\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x05R\rtotalRequests\x12=\n" +
	"\x0ffibonacci_stats\x18\x02 \x03(\v2\x14.stats.FibonacciStatR\x0efibonacciStats\"j\n" +
	"\rFibonacciStat\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\x12#\n" +
	"\rrequest_count\x18\x02 \x01(\x05R\frequestCount\x12&\n" +
	"\x0faverage_time_ms\x18\x03 \x01(\x01R\raverageTimeMs\"9\n" +
	"\rRecordRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x03R\bduration\"*\n" +
	"\x0eRecordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2z\n" +
	"\x05Stats\x127\n" +
	"\bRecordNo\x12\x14.stats.RecordRequest\x1a\x15.stats.RecordResponse\x128\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x14.stats.StatsResponseB\x1eZ\x1cyourrepo/proto/stats;statspbb\x06proto3"

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData []byte
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)))
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stats_proto_goTypes = []any{
	(*StatsResponse)(nil),  // 0: stats.StatsResponse
	(*FibonacciStat)(nil),  // 1: stats.FibonacciStat
	(*RecordRequest)(nil),  // 2: stats.RecordRequest
	(*RecordResponse)(nil), // 3: stats.RecordResponse
	(*emptypb.Empty)(nil),  // 4: google.protobuf.Empty
}
var file_stats_proto_depIdxs = []int32{
	1, // 0: stats.StatsResponse.fibonacci_stats:type_name -> stats.FibonacciStat
	2, // 1: stats.Stats.RecordNo:input_type -> stats.RecordRequest
	4, // 2: stats.Stats.GetStats:input_type -> google.protobuf.Empty
	3, // 3: stats.Stats.RecordNo:output_type -> stats.RecordResponse
	0, // 4: stats.Stats.GetStats:output_type -> stats.StatsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
